/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeepPockets */

#ifndef _Included_DeepPockets
#define _Included_DeepPockets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeepPockets
 * Method:    cacheNew
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_DeepPockets_cacheNew
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DeepPockets
 * Method:    cacheSetObject
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DeepPockets_cacheSetObject
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     DeepPockets
 * Method:    cacheSetObjectWithCost
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_DeepPockets_cacheSetObjectWithCost
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

/*
 * Class:     DeepPockets
 * Method:    cacheObjectForKey
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DeepPockets_cacheObjectForKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     DeepPockets
 * Method:    cacheRemoveObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DeepPockets_cacheRemoveObject
  (JNIEnv *, jclass);

/*
 * Class:     DeepPockets
 * Method:    cacheRemoveAllObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DeepPockets_cacheRemoveAllObjects
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
